/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;
import Controller.*;

/**
 *
 * @author isard
 */

public class AdminView extends javax.swing.JFrame {
    private int posX, posY;
    /**
     * Creates new form AdminSelect
     */
    
    
    public AdminView() {
        initComponents();
        LabelCompleteName.setText(Controller.getUserName());
        setLocationRelativeTo(null);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelBackground = new javax.swing.JPanel();
        Content = new javax.swing.JPanel();
        LabelAdminPanel = new javax.swing.JLabel();
        Selector = new javax.swing.JPanel();
        PanelBtnCourts = new javax.swing.JPanel();
        LabelCourts = new javax.swing.JLabel();
        LabelCourtsImage = new javax.swing.JLabel();
        PanelBtnUsers = new javax.swing.JPanel();
        LabelUsersImage = new javax.swing.JLabel();
        LabelUsers = new javax.swing.JLabel();
        CreateCourt = new javax.swing.JPanel();
        UserInfo = new javax.swing.JPanel();
        Users = new javax.swing.JPanel();
        CourtInfo = new javax.swing.JPanel();
        Courts = new javax.swing.JPanel();
        CourtSample = new javax.swing.JPanel();
        LabelCourtName = new javax.swing.JLabel();
        LabelCourtImage = new javax.swing.JLabel();
        LabelCourtState = new javax.swing.JLabel();
        BtnCourt = new javax.swing.JButton();
        BtnReturn = new javax.swing.JButton();
        BtnAdd = new javax.swing.JButton();
        CreateUser = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        LabelLogo = new javax.swing.JLabel();
        LabelCompleteName = new javax.swing.JLabel();
        LabelTitle = new javax.swing.JLabel();
        BtnClose = new javax.swing.JButton();
        BtnLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1192, 582));
        setUndecorated(true);

        PanelBackground.setBackground(new java.awt.Color(0, 56, 64));
        PanelBackground.setMaximumSize(new java.awt.Dimension(1192, 582));
        PanelBackground.setMinimumSize(new java.awt.Dimension(1192, 582));
        PanelBackground.setPreferredSize(new java.awt.Dimension(1192, 582));
        PanelBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Content.setBackground(new java.awt.Color(0, 56, 64));
        Content.setMaximumSize(new java.awt.Dimension(1198, 482));
        Content.setMinimumSize(new java.awt.Dimension(1198, 482));
        Content.setPreferredSize(new java.awt.Dimension(1198, 482));
        Content.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelAdminPanel.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        LabelAdminPanel.setForeground(new java.awt.Color(255, 255, 255));
        LabelAdminPanel.setText("Administrator Panel");
        Content.add(LabelAdminPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, -1, -1));

        Selector.setBackground(new java.awt.Color(0, 90, 91));
        Selector.setMaximumSize(new java.awt.Dimension(934, 362));
        Selector.setMinimumSize(new java.awt.Dimension(934, 362));
        Selector.setPreferredSize(new java.awt.Dimension(934, 362));
        Selector.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelBtnCourts.setBackground(new java.awt.Color(0, 115, 105));
        PanelBtnCourts.setMaximumSize(new java.awt.Dimension(350, 311));
        PanelBtnCourts.setMinimumSize(new java.awt.Dimension(350, 311));
        PanelBtnCourts.setPreferredSize(new java.awt.Dimension(350, 311));
        PanelBtnCourts.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PanelBtnCourtsFocusGained(evt);
            }
        });
        PanelBtnCourts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelBtnCourtsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelBtnCourtsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelBtnCourtsMouseExited(evt);
            }
        });
        PanelBtnCourts.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelCourts.setFont(new java.awt.Font("Arial", 1, 28)); // NOI18N
        LabelCourts.setForeground(new java.awt.Color(255, 255, 255));
        LabelCourts.setText("Courts");
        PanelBtnCourts.add(LabelCourts, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 45, -1, -1));

        LabelCourtsImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/courts.png"))); // NOI18N
        LabelCourtsImage.setFocusable(false);
        PanelBtnCourts.add(LabelCourtsImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 125, -1, -1));

        Selector.add(PanelBtnCourts, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 25, -1, -1));

        PanelBtnUsers.setBackground(new java.awt.Color(0, 115, 105));
        PanelBtnUsers.setFocusable(false);
        PanelBtnUsers.setMaximumSize(new java.awt.Dimension(350, 311));
        PanelBtnUsers.setMinimumSize(new java.awt.Dimension(350, 311));
        PanelBtnUsers.setPreferredSize(new java.awt.Dimension(350, 311));
        PanelBtnUsers.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PanelBtnUsersFocusGained(evt);
            }
        });
        PanelBtnUsers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelBtnUsersMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelBtnUsersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelBtnUsersMouseExited(evt);
            }
        });
        PanelBtnUsers.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelUsersImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/users.png"))); // NOI18N
        PanelBtnUsers.add(LabelUsersImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 125, -1, -1));

        LabelUsers.setFont(new java.awt.Font("Arial", 1, 28)); // NOI18N
        LabelUsers.setForeground(new java.awt.Color(255, 255, 255));
        LabelUsers.setText("Users");
        PanelBtnUsers.add(LabelUsers, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 46, -1, -1));

        Selector.add(PanelBtnUsers, new org.netbeans.lib.awtextra.AbsoluteConstraints(525, 25, -1, -1));

        Content.add(Selector, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, -1, -1));

        CreateCourt.setVisible(false);
        CreateCourt.setBackground(new java.awt.Color(0, 90, 91));
        CreateCourt.setMaximumSize(new java.awt.Dimension(934, 362));
        CreateCourt.setMinimumSize(new java.awt.Dimension(934, 362));
        CreateCourt.setPreferredSize(new java.awt.Dimension(934, 362));
        CreateCourt.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        Content.add(CreateCourt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, -1, -1));

        UserInfo.setVisible(false);
        UserInfo.setBackground(new java.awt.Color(0, 90, 91));
        UserInfo.setMaximumSize(new java.awt.Dimension(934, 362));
        UserInfo.setMinimumSize(new java.awt.Dimension(934, 362));
        UserInfo.setPreferredSize(new java.awt.Dimension(934, 362));
        UserInfo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        Content.add(UserInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, -1, -1));

        Users.setVisible(false);
        Users.setBackground(new java.awt.Color(0, 90, 91));
        Users.setMaximumSize(new java.awt.Dimension(934, 362));
        Users.setMinimumSize(new java.awt.Dimension(934, 362));
        Users.setPreferredSize(new java.awt.Dimension(934, 362));
        Users.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        Content.add(Users, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, -1, -1));

        CourtInfo.setVisible(false);
        CourtInfo.setBackground(new java.awt.Color(0, 90, 91));
        CourtInfo.setMaximumSize(new java.awt.Dimension(934, 362));
        CourtInfo.setMinimumSize(new java.awt.Dimension(934, 362));
        CourtInfo.setPreferredSize(new java.awt.Dimension(934, 362));
        CourtInfo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        Content.add(CourtInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, -1, -1));

        Courts.setVisible(false);
        Courts.setBackground(new java.awt.Color(0, 90, 91));
        Courts.setMaximumSize(new java.awt.Dimension(934, 362));
        Courts.setMinimumSize(new java.awt.Dimension(934, 362));
        Courts.setPreferredSize(new java.awt.Dimension(934, 362));
        Courts.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CourtSample.setBackground(new java.awt.Color(0, 115, 105));
        CourtSample.setMaximumSize(new java.awt.Dimension(134, 152));
        CourtSample.setMinimumSize(new java.awt.Dimension(134, 152));
        CourtSample.setPreferredSize(new java.awt.Dimension(134, 152));
        CourtSample.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelCourtName.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        LabelCourtName.setForeground(new java.awt.Color(255, 255, 255));
        LabelCourtName.setText("Court 1");
        CourtSample.add(LabelCourtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 12, -1, -1));

        LabelCourtImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/court.png"))); // NOI18N
        CourtSample.add(LabelCourtImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        LabelCourtState.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        LabelCourtState.setForeground(new java.awt.Color(255, 255, 255));
        LabelCourtState.setText("Active");
        CourtSample.add(LabelCourtState, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 123, -1, -1));

        BtnCourt.setBackground(new java.awt.Color(0, 115, 105));
        BtnCourt.setBorder(null);
        BtnCourt.setBorderPainted(false);
        BtnCourt.setMaximumSize(new java.awt.Dimension(134, 152));
        BtnCourt.setMinimumSize(new java.awt.Dimension(134, 152));
        BtnCourt.setPreferredSize(new java.awt.Dimension(134, 152));
        CourtSample.add(BtnCourt, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Courts.add(CourtSample, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        BtnReturn.setBackground(new java.awt.Color(0, 56, 64));
        BtnReturn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/return.png"))); // NOI18N
        BtnReturn.setBorder(null);
        BtnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnReturnActionPerformed(evt);
            }
        });
        Courts.add(BtnReturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(902, -40, -1, -1));

        BtnAdd.setBackground(new java.awt.Color(0, 56, 64));
        BtnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add.png"))); // NOI18N
        BtnAdd.setBorder(null);
        Courts.add(BtnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(861, -40, -1, -1));

        Content.add(Courts, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, -1, -1));

        CreateUser.setVisible(false);
        CreateUser.setBackground(new java.awt.Color(0, 90, 91));
        CreateUser.setMaximumSize(new java.awt.Dimension(934, 362));
        CreateUser.setMinimumSize(new java.awt.Dimension(934, 362));
        CreateUser.setPreferredSize(new java.awt.Dimension(934, 362));
        CreateUser.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        Content.add(CreateUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, -1, -1));

        PanelBackground.add(Content, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, -1));

        Header.setBackground(new java.awt.Color(0, 56, 64));
        Header.setMaximumSize(new java.awt.Dimension(1192, 100));
        Header.setMinimumSize(new java.awt.Dimension(1192, 100));
        Header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                HeaderMouseDragged(evt);
            }
        });
        Header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HeaderMousePressed(evt);
            }
        });
        Header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/headerLogo.png"))); // NOI18N
        Header.add(LabelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        LabelCompleteName.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        LabelCompleteName.setForeground(new java.awt.Color(255, 255, 255));
        LabelCompleteName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LabelCompleteName.setMaximumSize(new java.awt.Dimension(280, 28));
        LabelCompleteName.setMinimumSize(new java.awt.Dimension(280, 28));
        LabelCompleteName.setPreferredSize(new java.awt.Dimension(280, 28));
        Header.add(LabelCompleteName, new org.netbeans.lib.awtextra.AbsoluteConstraints(772, 36, -1, -1));
        LabelCompleteName.setText(Controller.currentUser.getName() + Controller.currentUser.getSurnames());

        LabelTitle.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        LabelTitle.setForeground(new java.awt.Color(255, 255, 255));
        LabelTitle.setText("Booking of Padel Courts");
        Header.add(LabelTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 36, -1, -1));

        BtnClose.setBackground(new java.awt.Color(0, 56, 64));
        BtnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/close.png"))); // NOI18N
        BtnClose.setBorder(null);
        BtnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCloseActionPerformed(evt);
            }
        });
        Header.add(BtnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 36, -1, -1));

        BtnLogout.setBackground(new java.awt.Color(0, 56, 64));
        BtnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logout.png"))); // NOI18N
        BtnLogout.setBorder(null);
        BtnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLogoutActionPerformed(evt);
            }
        });
        Header.add(BtnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1075, 36, -1, -1));

        PanelBackground.add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCloseActionPerformed
        System.exit(0);
    }//GEN-LAST:event_BtnCloseActionPerformed

    private void HeaderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMouseDragged
        int newX = evt.getXOnScreen() - posX;
        int newY = evt.getYOnScreen() - posY;

        setLocation(newX, newY);
    }//GEN-LAST:event_HeaderMouseDragged

    private void HeaderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMousePressed
        posX = evt.getXOnScreen() - getX();
        posY = evt.getYOnScreen() - getY();
    }//GEN-LAST:event_HeaderMousePressed

    private void BtnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLogoutActionPerformed
        ButtonActions.logOut(true);
    }//GEN-LAST:event_BtnLogoutActionPerformed

    private void BtnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnReturnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnReturnActionPerformed

    private void PanelBtnCourtsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelBtnCourtsMouseClicked
        PanelBtnCourts.setBackground(new java.awt.Color(0,115,105));
        Selector.setVisible(false);
        Courts.setVisible(true);
    }//GEN-LAST:event_PanelBtnCourtsMouseClicked

    private void PanelBtnUsersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelBtnUsersMouseClicked
        PanelBtnUsers.setBackground(new java.awt.Color(0,115,105));
        Selector.setVisible(false);
        Users.setVisible(true);
    }//GEN-LAST:event_PanelBtnUsersMouseClicked

    private void PanelBtnCourtsFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PanelBtnCourtsFocusGained
        
    }//GEN-LAST:event_PanelBtnCourtsFocusGained

    private void PanelBtnUsersFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PanelBtnUsersFocusGained

    }//GEN-LAST:event_PanelBtnUsersFocusGained

    private void PanelBtnCourtsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelBtnCourtsMouseEntered
        PanelBtnCourts.setBackground(new java.awt.Color(0,140,129));
    }//GEN-LAST:event_PanelBtnCourtsMouseEntered

    private void PanelBtnCourtsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelBtnCourtsMouseExited
        PanelBtnCourts.setBackground(new java.awt.Color(0,115,105));
    }//GEN-LAST:event_PanelBtnCourtsMouseExited

    private void PanelBtnUsersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelBtnUsersMouseEntered
        PanelBtnUsers.setBackground(new java.awt.Color(0,140,129));
    }//GEN-LAST:event_PanelBtnUsersMouseEntered

    private void PanelBtnUsersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelBtnUsersMouseExited
        PanelBtnUsers.setBackground(new java.awt.Color(0,115,105));
    }//GEN-LAST:event_PanelBtnUsersMouseExited

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAdd;
    private javax.swing.JButton BtnClose;
    private javax.swing.JButton BtnCourt;
    private javax.swing.JButton BtnLogout;
    private javax.swing.JButton BtnReturn;
    public javax.swing.JPanel Content;
    public javax.swing.JPanel CourtInfo;
    private javax.swing.JPanel CourtSample;
    private javax.swing.JPanel Courts;
    public javax.swing.JPanel CreateCourt;
    public javax.swing.JPanel CreateUser;
    private javax.swing.JPanel Header;
    private javax.swing.JLabel LabelAdminPanel;
    private javax.swing.JLabel LabelCompleteName;
    private javax.swing.JLabel LabelCourtImage;
    private javax.swing.JLabel LabelCourtName;
    private javax.swing.JLabel LabelCourtState;
    private javax.swing.JLabel LabelCourts;
    private javax.swing.JLabel LabelCourtsImage;
    private javax.swing.JLabel LabelLogo;
    private javax.swing.JLabel LabelTitle;
    private javax.swing.JLabel LabelUsers;
    private javax.swing.JLabel LabelUsersImage;
    public javax.swing.JPanel PanelBackground;
    private javax.swing.JPanel PanelBtnCourts;
    private javax.swing.JPanel PanelBtnUsers;
    public javax.swing.JPanel Selector;
    public javax.swing.JPanel UserInfo;
    public javax.swing.JPanel Users;
    // End of variables declaration//GEN-END:variables
}
