/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;
import Controller.*;

/**
 *
 * @author isard
 */

public class AdminView extends javax.swing.JFrame {
    private int posX, posY;
    /**
     * Creates new form AdminSelect
     */
    
    
    public AdminView() {
        initComponents();
        LabelCompleteName.setText(Controller.getUserName());
        setLocationRelativeTo(null);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelBackground = new javax.swing.JPanel();
        Content = new javax.swing.JPanel();
        LabelAdminPanel = new javax.swing.JLabel();
        Courts = new javax.swing.JPanel();
        BtnReturn = new javax.swing.JButton();
        BtnAdd = new javax.swing.JButton();
        CourtsContent = new javax.swing.JPanel();
        CourtSample = new javax.swing.JPanel();
        LabelCourtName = new javax.swing.JLabel();
        LabelCourtImage = new javax.swing.JLabel();
        LabelCourtState = new javax.swing.JLabel();
        BtnCourt = new javax.swing.JButton();
        Selector = new javax.swing.JPanel();
        PanelBtnCourts = new javax.swing.JPanel();
        LabelCourts = new javax.swing.JLabel();
        LabelCourtsImage = new javax.swing.JLabel();
        PanelBtnUsers = new javax.swing.JPanel();
        CreateCourts = new javax.swing.JPanel();
        BtnReturn1 = new javax.swing.JButton();
        CreateCourtsContent = new javax.swing.JPanel();
        LabelUsersImage = new javax.swing.JLabel();
        LabelUsers = new javax.swing.JLabel();
        CreateCourt = new javax.swing.JPanel();
        UserInfo = new javax.swing.JPanel();
        Users = new javax.swing.JPanel();
        CourtInfo = new javax.swing.JPanel();
        BtnReturn5 = new javax.swing.JButton();
        CourtInfoContent = new javax.swing.JPanel();
        CreateUsers = new javax.swing.JPanel();
        BtnReturn2 = new javax.swing.JButton();
        CreateUsersContent = new javax.swing.JPanel();
        Users = new javax.swing.JPanel();
        BtnReturn3 = new javax.swing.JButton();
        BtnAdd3 = new javax.swing.JButton();
        UsersContent = new javax.swing.JPanel();
        UserInfo = new javax.swing.JPanel();
        BtnReturn4 = new javax.swing.JButton();
        UserInfoContent = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        LabelLogo = new javax.swing.JLabel();
        LabelCompleteName = new javax.swing.JLabel();
        LabelTitle = new javax.swing.JLabel();
        BtnClose = new javax.swing.JButton();
        BtnLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1192, 582));
        setUndecorated(true);

        PanelBackground.setBackground(new java.awt.Color(0, 56, 64));
        PanelBackground.setMaximumSize(new java.awt.Dimension(1192, 582));
        PanelBackground.setMinimumSize(new java.awt.Dimension(1192, 582));
        PanelBackground.setPreferredSize(new java.awt.Dimension(1192, 582));
        PanelBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Content.setBackground(new java.awt.Color(0, 56, 64));
        Content.setMaximumSize(new java.awt.Dimension(1198, 482));
        Content.setMinimumSize(new java.awt.Dimension(1198, 482));
        Content.setPreferredSize(new java.awt.Dimension(1198, 482));
        Content.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelAdminPanel.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        LabelAdminPanel.setForeground(new java.awt.Color(255, 255, 255));
        LabelAdminPanel.setText("Administrator Panel");
        Content.add(LabelAdminPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, -1, -1));

        Courts.setVisible(false);
        Courts.setBackground(new java.awt.Color(0, 56, 64));
        Courts.setMaximumSize(new java.awt.Dimension(934, 403));
        Courts.setMinimumSize(new java.awt.Dimension(934, 403));
        Courts.setName(""); // NOI18N
        Courts.setPreferredSize(new java.awt.Dimension(934, 403));
        Courts.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnReturn.setBackground(new java.awt.Color(0, 56, 64));
        BtnReturn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/return.png"))); // NOI18N
        BtnReturn.setBorder(null);
        BtnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnReturnActionPerformed(evt);
            }
        });
        Courts.add(BtnReturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(902, 0, -1, -1));

        BtnAdd.setBackground(new java.awt.Color(0, 56, 64));
        BtnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add.png"))); // NOI18N
        BtnAdd.setBorder(null);
        BtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAddActionPerformed(evt);
            }
        });
        Courts.add(BtnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(861, 0, -1, -1));

        CourtsContent.setBackground(new java.awt.Color(0, 90, 91));
        CourtsContent.setMaximumSize(new java.awt.Dimension(934, 362));
        CourtsContent.setMinimumSize(new java.awt.Dimension(934, 362));
        CourtsContent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CourtSample.setBackground(new java.awt.Color(0, 115, 105));
        CourtSample.setMaximumSize(new java.awt.Dimension(134, 152));
        CourtSample.setMinimumSize(new java.awt.Dimension(134, 152));
        CourtSample.setPreferredSize(new java.awt.Dimension(134, 152));
        CourtSample.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelCourtName.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        LabelCourtName.setForeground(new java.awt.Color(255, 255, 255));
        LabelCourtName.setText("Court 1");
        CourtSample.add(LabelCourtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 12, -1, -1));

        LabelCourtImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/court.png"))); // NOI18N
        CourtSample.add(LabelCourtImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        LabelCourtState.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        LabelCourtState.setForeground(new java.awt.Color(255, 255, 255));
        LabelCourtState.setText("Active");
        CourtSample.add(LabelCourtState, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 123, -1, -1));

        BtnCourt.setBackground(new java.awt.Color(0, 115, 105));
        BtnCourt.setBorder(null);
        BtnCourt.setBorderPainted(false);
        BtnCourt.setMaximumSize(new java.awt.Dimension(134, 152));
        BtnCourt.setMinimumSize(new java.awt.Dimension(134, 152));
        BtnCourt.setPreferredSize(new java.awt.Dimension(134, 152));
        CourtSample.add(BtnCourt, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        CourtsContent.add(CourtSample, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        Courts.add(CourtsContent, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 940, 360));

        Content.add(Courts, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, -1, -1));

        Selector.setBackground(new java.awt.Color(0, 90, 91));
        Selector.setMaximumSize(new java.awt.Dimension(934, 362));
        Selector.setMinimumSize(new java.awt.Dimension(934, 362));
        Selector.setPreferredSize(new java.awt.Dimension(934, 362));
        Selector.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelBtnCourts.setBackground(new java.awt.Color(0, 115, 105));
        PanelBtnCourts.setMaximumSize(new java.awt.Dimension(350, 311));
        PanelBtnCourts.setMinimumSize(new java.awt.Dimension(350, 311));
        PanelBtnCourts.setPreferredSize(new java.awt.Dimension(350, 311));
        PanelBtnCourts.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PanelBtnCourtsFocusGained(evt);
            }
        });
        PanelBtnCourts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelBtnCourtsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelBtnCourtsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelBtnCourtsMouseExited(evt);
            }
        });
        PanelBtnCourts.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelCourts.setFont(new java.awt.Font("Arial", 1, 28)); // NOI18N
        LabelCourts.setForeground(new java.awt.Color(255, 255, 255));
        LabelCourts.setText("Courts");
        PanelBtnCourts.add(LabelCourts, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 45, -1, -1));

        LabelCourtsImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/courts.png"))); // NOI18N
        LabelCourtsImage.setFocusable(false);
        PanelBtnCourts.add(LabelCourtsImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 125, -1, -1));

        Selector.add(PanelBtnCourts, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 25, -1, -1));

        PanelBtnUsers.setBackground(new java.awt.Color(0, 115, 105));
        PanelBtnUsers.setFocusable(false);
        PanelBtnUsers.setMaximumSize(new java.awt.Dimension(350, 311));
        PanelBtnUsers.setMinimumSize(new java.awt.Dimension(350, 311));
        PanelBtnUsers.setPreferredSize(new java.awt.Dimension(350, 311));
        PanelBtnUsers.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PanelBtnUsersFocusGained(evt);
            }
        });
        PanelBtnUsers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelBtnUsersMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelBtnUsersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelBtnUsersMouseExited(evt);
            }
        });
        PanelBtnUsers.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelUsersImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/users.png"))); // NOI18N
        PanelBtnUsers.add(LabelUsersImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 125, -1, -1));

        LabelUsers.setFont(new java.awt.Font("Arial", 1, 28)); // NOI18N
        LabelUsers.setForeground(new java.awt.Color(255, 255, 255));
        LabelUsers.setText("Users");
        PanelBtnUsers.add(LabelUsers, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 46, -1, -1));

        Selector.add(PanelBtnUsers, new org.netbeans.lib.awtextra.AbsoluteConstraints(525, 25, -1, -1));

        Content.add(Selector, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, -1, -1));

        CreateCourts.setVisible(false);
        CreateCourts.setBackground(new java.awt.Color(0, 56, 64));
        CreateCourts.setMaximumSize(new java.awt.Dimension(934, 403));
        CreateCourts.setMinimumSize(new java.awt.Dimension(934, 403));
        CreateCourts.setName(""); // NOI18N
        CreateCourts.setPreferredSize(new java.awt.Dimension(934, 403));
        CreateCourts.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnReturn1.setBackground(new java.awt.Color(0, 56, 64));
        BtnReturn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/return.png"))); // NOI18N
        BtnReturn1.setBorder(null);
        BtnReturn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnReturn1ActionPerformed(evt);
            }
        });
        CreateCourts.add(BtnReturn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(902, 0, -1, -1));

        CreateCourtsContent.setBackground(new java.awt.Color(0, 90, 91));
        CreateCourtsContent.setMaximumSize(new java.awt.Dimension(934, 362));
        CreateCourtsContent.setMinimumSize(new java.awt.Dimension(934, 362));
        CreateCourtsContent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        CreateCourts.add(CreateCourtsContent, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 940, 360));

        Content.add(CreateCourts, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, -1, -1));

        CourtInfo.setVisible(false);
        CourtInfo.setBackground(new java.awt.Color(0, 56, 64));
        CourtInfo.setMaximumSize(new java.awt.Dimension(934, 403));
        CourtInfo.setMinimumSize(new java.awt.Dimension(934, 403));
        CourtInfo.setName(""); // NOI18N
        CourtInfo.setPreferredSize(new java.awt.Dimension(934, 403));
        CourtInfo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnReturn5.setBackground(new java.awt.Color(0, 56, 64));
        BtnReturn5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/return.png"))); // NOI18N
        BtnReturn5.setBorder(null);
        BtnReturn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnReturn5ActionPerformed(evt);
            }
        });
        CourtInfo.add(BtnReturn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(902, 0, -1, -1));

        CourtInfoContent.setBackground(new java.awt.Color(0, 90, 91));
        CourtInfoContent.setMaximumSize(new java.awt.Dimension(934, 362));
        CourtInfoContent.setMinimumSize(new java.awt.Dimension(934, 362));
        CourtInfoContent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        CourtInfo.add(CourtInfoContent, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 940, 360));

        Content.add(CourtInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, -1, -1));

        CreateUsers.setVisible(false);
        CreateUsers.setBackground(new java.awt.Color(0, 56, 64));
        CreateUsers.setMaximumSize(new java.awt.Dimension(934, 403));
        CreateUsers.setMinimumSize(new java.awt.Dimension(934, 403));
        CreateUsers.setName(""); // NOI18N
        CreateUsers.setPreferredSize(new java.awt.Dimension(934, 403));
        CreateUsers.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnReturn2.setBackground(new java.awt.Color(0, 56, 64));
        BtnReturn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/return.png"))); // NOI18N
        BtnReturn2.setBorder(null);
        BtnReturn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnReturn2ActionPerformed(evt);
            }
        });
        CreateUsers.add(BtnReturn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(902, 0, -1, -1));

        CreateUsersContent.setBackground(new java.awt.Color(0, 90, 91));
        CreateUsersContent.setMaximumSize(new java.awt.Dimension(934, 362));
        CreateUsersContent.setMinimumSize(new java.awt.Dimension(934, 362));
        CreateUsersContent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        CreateUsers.add(CreateUsersContent, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 940, 360));

        Content.add(CreateUsers, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, -1, -1));

        Users.setVisible(false);
        Users.setBackground(new java.awt.Color(0, 56, 64));
        Users.setMaximumSize(new java.awt.Dimension(934, 403));
        Users.setMinimumSize(new java.awt.Dimension(934, 403));
        Users.setName(""); // NOI18N
        Users.setPreferredSize(new java.awt.Dimension(934, 403));
        Users.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnReturn3.setBackground(new java.awt.Color(0, 56, 64));
        BtnReturn3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/return.png"))); // NOI18N
        BtnReturn3.setBorder(null);
        BtnReturn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnReturn3ActionPerformed(evt);
            }
        });
        Users.add(BtnReturn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(902, 0, -1, -1));

        BtnAdd3.setBackground(new java.awt.Color(0, 56, 64));
        BtnAdd3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add.png"))); // NOI18N
        BtnAdd3.setBorder(null);
        BtnAdd3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAdd3ActionPerformed(evt);
            }
        });
        Users.add(BtnAdd3, new org.netbeans.lib.awtextra.AbsoluteConstraints(861, 0, -1, -1));

        UsersContent.setBackground(new java.awt.Color(0, 90, 91));
        UsersContent.setMaximumSize(new java.awt.Dimension(934, 362));
        UsersContent.setMinimumSize(new java.awt.Dimension(934, 362));
        UsersContent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        Users.add(UsersContent, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 940, 360));

        Content.add(Users, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, -1, -1));

        UserInfo.setVisible(false);
        UserInfo.setBackground(new java.awt.Color(0, 56, 64));
        UserInfo.setMaximumSize(new java.awt.Dimension(934, 403));
        UserInfo.setMinimumSize(new java.awt.Dimension(934, 403));
        UserInfo.setName(""); // NOI18N
        UserInfo.setPreferredSize(new java.awt.Dimension(934, 403));
        UserInfo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnReturn4.setBackground(new java.awt.Color(0, 56, 64));
        BtnReturn4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/return.png"))); // NOI18N
        BtnReturn4.setBorder(null);
        BtnReturn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnReturn4ActionPerformed(evt);
            }
        });
        UserInfo.add(BtnReturn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(902, 0, -1, -1));

        UserInfoContent.setBackground(new java.awt.Color(0, 90, 91));
        UserInfoContent.setMaximumSize(new java.awt.Dimension(934, 362));
        UserInfoContent.setMinimumSize(new java.awt.Dimension(934, 362));
        UserInfoContent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        UserInfo.add(UserInfoContent, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 940, 360));

        Content.add(UserInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, -1, -1));

        PanelBackground.add(Content, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, -1));

        Header.setBackground(new java.awt.Color(0, 56, 64));
        Header.setMaximumSize(new java.awt.Dimension(1192, 100));
        Header.setMinimumSize(new java.awt.Dimension(1192, 100));
        Header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                HeaderMouseDragged(evt);
            }
        });
        Header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HeaderMousePressed(evt);
            }
        });
        Header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/headerLogo.png"))); // NOI18N
        Header.add(LabelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        LabelCompleteName.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        LabelCompleteName.setForeground(new java.awt.Color(255, 255, 255));
        LabelCompleteName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LabelCompleteName.setMaximumSize(new java.awt.Dimension(280, 28));
        LabelCompleteName.setMinimumSize(new java.awt.Dimension(280, 28));
        LabelCompleteName.setPreferredSize(new java.awt.Dimension(280, 28));
        Header.add(LabelCompleteName, new org.netbeans.lib.awtextra.AbsoluteConstraints(772, 36, -1, -1));
        LabelCompleteName.setText(Controller.currentUser.getName() + Controller.currentUser.getSurnames());

        LabelTitle.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        LabelTitle.setForeground(new java.awt.Color(255, 255, 255));
        LabelTitle.setText("Booking of Padel Courts");
        Header.add(LabelTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 36, -1, -1));

        BtnClose.setBackground(new java.awt.Color(0, 56, 64));
        BtnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/close.png"))); // NOI18N
        BtnClose.setBorder(null);
        BtnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCloseActionPerformed(evt);
            }
        });
        Header.add(BtnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 36, -1, -1));

        BtnLogout.setBackground(new java.awt.Color(0, 56, 64));
        BtnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logout.png"))); // NOI18N
        BtnLogout.setBorder(null);
        BtnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLogoutActionPerformed(evt);
            }
        });
        Header.add(BtnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1075, 36, -1, -1));

        PanelBackground.add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCloseActionPerformed
        System.exit(0);
    }//GEN-LAST:event_BtnCloseActionPerformed

    private void HeaderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMouseDragged
        int newX = evt.getXOnScreen() - posX;
        int newY = evt.getYOnScreen() - posY;

        setLocation(newX, newY);
    }//GEN-LAST:event_HeaderMouseDragged

    private void HeaderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMousePressed
        posX = evt.getXOnScreen() - getX();
        posY = evt.getYOnScreen() - getY();
    }//GEN-LAST:event_HeaderMousePressed

    private void BtnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLogoutActionPerformed
        ButtonActions.logOut(true);
    }//GEN-LAST:event_BtnLogoutActionPerformed

    private void BtnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnReturnActionPerformed
        Selector.setVisible(true);
        Courts.setVisible(false);
    }//GEN-LAST:event_BtnReturnActionPerformed

    private void PanelBtnCourtsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelBtnCourtsMouseClicked
        PanelBtnCourts.setBackground(new java.awt.Color(0,115,105));
        Selector.setVisible(false);
        Courts.setVisible(true);
        Selector.setVisible(false);
    }//GEN-LAST:event_PanelBtnCourtsMouseClicked

    private void PanelBtnUsersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelBtnUsersMouseClicked
        PanelBtnUsers.setBackground(new java.awt.Color(0,115,105));
        Selector.setVisible(false);
        Users.setVisible(true);
    }//GEN-LAST:event_PanelBtnUsersMouseClicked

    private void BtnReturn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnReturn1ActionPerformed
        Courts.setVisible(true);
        CreateCourts.setVisible(false);
    }//GEN-LAST:event_BtnReturn1ActionPerformed

    private void BtnReturn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnReturn2ActionPerformed
        Users.setVisible(true);
        CreateUsers.setVisible(false);
    }//GEN-LAST:event_BtnReturn2ActionPerformed

    private void BtnReturn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnReturn3ActionPerformed
        Selector.setVisible(true);
        Users.setVisible(false);
    }//GEN-LAST:event_BtnReturn3ActionPerformed

    private void BtnReturn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnReturn4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnReturn4ActionPerformed

    private void BtnReturn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnReturn5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnReturn5ActionPerformed

    private void BtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAddActionPerformed
        CreateCourts.setVisible(true);
        Courts.setVisible(false);
    }//GEN-LAST:event_BtnAddActionPerformed

    private void BtnAdd3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAdd3ActionPerformed
        CreateUsers.setVisible(true);
        Users.setVisible(false);
    }//GEN-LAST:event_BtnAdd3ActionPerformed
    private void PanelBtnCourtsFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PanelBtnCourtsFocusGained
        
    }//GEN-LAST:event_PanelBtnCourtsFocusGained

    private void PanelBtnUsersFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PanelBtnUsersFocusGained

    }//GEN-LAST:event_PanelBtnUsersFocusGained

    private void PanelBtnCourtsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelBtnCourtsMouseEntered
        PanelBtnCourts.setBackground(new java.awt.Color(0,140,129));
    }//GEN-LAST:event_PanelBtnCourtsMouseEntered

    private void PanelBtnCourtsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelBtnCourtsMouseExited
        PanelBtnCourts.setBackground(new java.awt.Color(0,115,105));
    }//GEN-LAST:event_PanelBtnCourtsMouseExited

    private void PanelBtnUsersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelBtnUsersMouseEntered
        PanelBtnUsers.setBackground(new java.awt.Color(0,140,129));
    }//GEN-LAST:event_PanelBtnUsersMouseEntered

    private void PanelBtnUsersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelBtnUsersMouseExited
        PanelBtnUsers.setBackground(new java.awt.Color(0,115,105));
    }//GEN-LAST:event_PanelBtnUsersMouseExited

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAdd;
    private javax.swing.JButton BtnAdd3;
    private javax.swing.JButton BtnClose;
    private javax.swing.JButton BtnCourt;
    private javax.swing.JButton BtnLogout;
    private javax.swing.JButton BtnReturn;
    private javax.swing.JButton BtnReturn1;
    private javax.swing.JButton BtnReturn2;
    private javax.swing.JButton BtnReturn3;
    private javax.swing.JButton BtnReturn4;
    private javax.swing.JButton BtnReturn5;
    public javax.swing.JPanel Content;
    private javax.swing.JPanel CourtInfo;
    private javax.swing.JPanel CourtInfoContent;
    private javax.swing.JPanel CourtSample;
    private javax.swing.JPanel Courts;
    private javax.swing.JPanel CourtsContent;
    private javax.swing.JPanel CreateCourts;
    private javax.swing.JPanel CreateCourtsContent;
    private javax.swing.JPanel CreateUsers;
    private javax.swing.JPanel CreateUsersContent;
    private javax.swing.JPanel Header;
    private javax.swing.JLabel LabelAdminPanel;
    private javax.swing.JLabel LabelCompleteName;
    private javax.swing.JLabel LabelCourtImage;
    private javax.swing.JLabel LabelCourtName;
    private javax.swing.JLabel LabelCourtState;
    private javax.swing.JLabel LabelCourts;
    private javax.swing.JLabel LabelCourtsImage;
    private javax.swing.JLabel LabelLogo;
    private javax.swing.JLabel LabelTitle;
    private javax.swing.JLabel LabelUsers;
    private javax.swing.JLabel LabelUsersImage;
    public javax.swing.JPanel PanelBackground;
    private javax.swing.JPanel PanelBtnCourts;
    private javax.swing.JPanel PanelBtnUsers;
    public javax.swing.JPanel Selector;
    private javax.swing.JPanel UserInfo;
    private javax.swing.JPanel UserInfoContent;
    private javax.swing.JPanel Users;
    private javax.swing.JPanel UsersContent;
    // End of variables declaration//GEN-END:variables
}
