/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

/**
 *
 * @author isard
 */
public class LoginError extends javax.swing.JFrame {

    private int posX, posY;
    
    public LoginError() {
        initComponents();
        
        setLocationRelativeTo(null);
        
        addMouseListener(new MouseAdapter() {
            public void mousePressed(MouseEvent e) {
                posX = e.getX();
                posY = e.getY();
            }
        });

        addMouseMotionListener(new MouseAdapter() {
            public void mouseDragged(MouseEvent e) {
                int x = e.getXOnScreen() - posX;
                int y = e.getYOnScreen() - posY;
                setLocation(x, y);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelBackground = new javax.swing.JPanel();
        LabelError = new javax.swing.JLabel();
        BtnExit = new javax.swing.JButton();
        LabelLogo = new javax.swing.JLabel();
        BtnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        PanelBackground.setBackground(new java.awt.Color(0, 56, 64));
        PanelBackground.setMaximumSize(new java.awt.Dimension(417, 582));
        PanelBackground.setMinimumSize(new java.awt.Dimension(417, 582));
        PanelBackground.setPreferredSize(new java.awt.Dimension(417, 582));
        PanelBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelError.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        LabelError.setForeground(new java.awt.Color(255, 255, 255));
        LabelError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelError.setText("<html><center>Unable to connect to database. <br> <br>\nPlease, try later or contact with the administrator.</center></html>");
        LabelError.setFocusable(false);
        LabelError.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        LabelError.setMaximumSize(new java.awt.Dimension(186, 114));
        LabelError.setMinimumSize(new java.awt.Dimension(186, 114));
        LabelError.setPreferredSize(new java.awt.Dimension(186, 114));
        PanelBackground.add(LabelError, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 271, 186, 114));
        LabelError.getAccessibleContext().setAccessibleName("Unable to connect to database.  Please, try later or contact with the administrator.");
        LabelError.getAccessibleContext().setAccessibleDescription("");

        BtnExit.setBackground(new java.awt.Color(0, 115, 105));
        BtnExit.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        BtnExit.setForeground(new java.awt.Color(255, 255, 255));
        BtnExit.setText("Exit");
        BtnExit.setMaximumSize(new java.awt.Dimension(236, 50));
        BtnExit.setMinimumSize(new java.awt.Dimension(236, 50));
        BtnExit.setPreferredSize(new java.awt.Dimension(236, 50));
        BtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnExitActionPerformed(evt);
            }
        });
        PanelBackground.add(BtnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 486, -1, -1));

        LabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"))); // NOI18N
        LabelLogo.setText("jLabel1");
        LabelLogo.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"))); // NOI18N
        LabelLogo.setMaximumSize(new java.awt.Dimension(265, 257));
        LabelLogo.setMinimumSize(new java.awt.Dimension(265, 257));
        LabelLogo.setPreferredSize(new java.awt.Dimension(265, 257));
        PanelBackground.add(LabelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 14, -1, 257));

        BtnClose.setBackground(new java.awt.Color(0, 56, 64));
        BtnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/close.png"))); // NOI18N
        BtnClose.setBorder(null);
        BtnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCloseActionPerformed(evt);
            }
        });
        PanelBackground.add(BtnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 14, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_BtnExitActionPerformed

    private void BtnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCloseActionPerformed
        System.exit(0);
    }//GEN-LAST:event_BtnCloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginError.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginError.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginError.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginError.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginError().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnClose;
    private javax.swing.JButton BtnExit;
    private javax.swing.JLabel LabelError;
    private javax.swing.JLabel LabelLogo;
    private javax.swing.JPanel PanelBackground;
    // End of variables declaration//GEN-END:variables
}
